### ISSUE TITLE
Deploy failure due to YAML structure change

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#27]
```
"ERROR: Failed to fetch recommendation title for T Q.5051  3/20"
bundler: failed to load command: jekyll (/Users/me/.rbenv/versions/2.6.5/bin/jekyll)
ArgumentError: comparison of Time with Date failed
  /Users/me/src/ituob/ituob.org/_plugins/issue_data_reader.rb:125:in `<'
  /Users/me/src/ituob/ituob.org/_plugins/issue_data_reader.rb:125:in `block in read_ob_issues'
  /Users/me/src/ituob/ituob.org/_plugins/issue_data_reader.rb:124:in `select'
  /Users/me/src/ituob/ituob.org/_plugins/issue_data_reader.rb:124:in `read_ob_issues'
  /Users/me/src/ituob/ituob.org/_plugins/issue_data_reader.rb:273:in `generate'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:175:in `block in generate'

...
```

**Comment by strogonoff** [comment]
This particular error cannot be reproduced anymore; the other build failure was pertaining to localization tag and was handled in https://github.com/ituob/ituob.org/commit/cc60d9bc13266ddfbe6dffce0d56e3a37f8efeb8 (build pending).

**Comment by strogonoff** [comment]
(Build succeeded)

**Comment by ronaldtse** [comment]
Thanks @strogonoff!
